### ISSUE TITLE
修改圆角无效啊？

### ISSUE THREAD

**Issue by GanZhiXiong** [hankbigoldli/electron-vue-shadow-radius#1]
在macOS下面，我修改#app的border-radius为50px，代码如下
``` css
#app {
  box-shadow: 0px 1px 7px #333333;
  background: white;
  border-radius: 50px;
  height: 100%;
}
```
然而圆角并没有变，什么情况呢？
![image](https://user-images.githubusercontent.com/27394631/69786525-91dc1200-11f5-11ea-9f70-277ff109e208.png)
